"""
Django settings for botentry project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "@&u25i5t*lg*!6c*5isukrzl57xn=v(xi1%77pf7&e_0!kp4q5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.trades'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'botentry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'botentry.wsgi.application'

# BINANCE VARIABLES

BINANCE_API_KEY = os.environ.get("BOT_ENTRY_BINANCE_API_KEY", None)
BINANCE_API_SECRET = os.environ.get("BOT_ENTRY_BINANCE_API_SECRET", None)

# AWS VARIABLES

AWS_ACCESS_KEY_ID = os.environ.get("BOT_ENTRY_AWS_ACCESS_KEY_ID", None)
AWS_SECRET_ACCESS_KEY = os.environ.get("BOT_ENTRY_AWS_SECRET_ACCESS_KEY", None)
AWS_BUCKET = os.environ.get("BOT_ENTRY_AWS_BUCKET", None)

# FACEBOOK VARIABLES

FACEBOOK_PAGE_ID = "106356054887194"
FACEBOOK_ACCESS_TOKEN = "EAAJUMmpPZB9EBALN9zCi0G7kQfrpfjqq4iZCYyMFZCGbTM30HuzPgmzgLviZCHdL7DVNXtFU3BFebi6AD23iGGtVXVXMMjM5033tEo5Tc03SCV2oFJZCnJUIpINZA4IvjxOyxZAlXUkq4oPFJqlytGLi2EZCqxLaVn0rjDYUIWXVvxSTZCQMjEfJb"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get("BOT_ENTRY_DATABASE_NAME", None),
        'USER': os.environ.get("BOT_ENTRY_DATABASE_USER", None),
        'PASSWORD': os.environ.get("BOT_ENTRY_DATABASE_PASSWORD", None),
        'HOST': 'localhost', #os.environ.get("BOT_ENTRY_DATABASE_HOST", None),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
