# Generated by Django 3.1.7 on 2021-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('encoded_variables_quantity', models.IntegerField()),
                ('mutation_intensity', models.IntegerField()),
                ('dna', models.TextField()),
                ('score', models.FloatField()),
                ('min_value', models.IntegerField()),
                ('pair', models.CharField(max_length=10)),
                ('temp', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='USDTPair',
        ),
    ]
