# Generated by Django 3.1.7 on 2021-06-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210625_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='max_value',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
