# Generated by Django 3.1.7 on 2021-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_individual_max_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10)),
                ('operation', models.CharField(max_length=10)),
                ('money', models.FloatField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('error', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
