# Generated by Django 3.1.7 on 2021-06-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
