# Generated by Django 3.1.7 on 2021-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20210630_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='percent',
            field=models.FloatField(default=0.02),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='percent_divisor_increment',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
